services:
  uex.contactbook.mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: uex.contactbook.mssql
    ports: 
      - 1433:1433
    environment:
      - "ACCEPT_EULA=Y"
      - "MSSQL_SA_PASSWORD=S@cr#t1_01"
      - "MSSQL_PID=Evaluation"
    networks:
      - live-network
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets

  uex.contactbook.rabbitmq:
    image: rabbitmq:3-management
    container_name: uex.contactbook.rabbitmq
    ports: 
      - "5672:5672"   # RabbitMQ default port
      - "15672:15672" # RabbitMQ management plugin port
    hostname: uex.contactbook.rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: uexmanager
      RABBITMQ_DEFAULT_PASS: S@cr#t1_01

  uex.contactbook.api:
    image: uex.contactbook.api
    container_name: uex.contactbook.api
    build:
      context: .
      dockerfile: .\Uex.Contactbook.Api\Dockerfile
    ports: 
      - 8080:8080
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTP_PORTS: 8080
    networks:
      - live-network
    depends_on: 
      - uex.contactbook.mssql
      - uex.contactbook.rabbitmq
    restart: always

  uex.contactbook.site:
    image: uex.contactbook.site
    container_name: uex.contactbook.site
    build:
      context: ..\ContactBookSite
      dockerfile: Dockerfile
    ports: 
      - 4400:8083
    networks:
      - live-network
    depends_on: 
      - uex.contactbook.api
networks:
  live-network:
    driver: bridge

